//package com.biogenholdings.InventoryMgtSystem.services.impl;
//
//
//
//import com.biogenholdings.InventoryMgtSystem.repositories.ReportRepository;
//
//import com.biogenholdings.InventoryMgtSystem.services.ChatService;
//
//import com.biogenholdings.InventoryMgtSystem.services.GeminiService;
//
//import com.biogenholdings.InventoryMgtSystem.services.IReportService;
//
//import com.biogenholdings.InventoryMgtSystem.services.ProductService;
//
//import lombok.RequiredArgsConstructor;
//
//import org.springframework.stereotype.Service;
//
//
//
//@Service
//
//@RequiredArgsConstructor
//
//public class ChatServiceImpl implements ChatService {
//
//
//
//    private final GeminiService geminiService;
//
//    private final ReportRepository reportRepository;
//
//
//
//    public Object process(String message) {
//
//
//
//// String aiResponse = geminiService.askGemini(message);
//
////
//
//// String action = extractAction(aiResponse);
//
////
//
//// switch (action) {
//
////
//
//// case "GET_LOW_STOCK":
//
//// return reportRepository.getLowStockItems();
//
////
//
//// case "GET_TOP_CUSTOMERS":
//
//// return reportRepository.getTopCustomers();
//
////
//
//// default:
//
//// return "I didn’t understand your request.";
//
//// }
//
//
//
//        String intentPrompt = "Analyze this user request: '" + message + "'. " +
//
//                "Reply with ONLY one keyword: GET_LOW_STOCK, GET_TOP_CUSTOMERS, or UNKNOWN.";
//
//        String intentRaw = geminiService.askGemini(intentPrompt).trim();
//
//
//
//// 🔥 The Fix: Remove everything that isn't an uppercase letter or underscore
//
//        String intent = intentRaw.replaceAll("[^A-Z_]", "");
//
//
//
//        System.out.println("DEBUG: Raw Intent from Gemini: [" + intentRaw + "]");
//
//        System.out.println("DEBUG: Cleaned Intent: [" + intent + "]");
//
//
//
//// 2. Fetch Data
//
//        Object rawData;
//
//        switch (intent) {
//
//            case "GET_LOW_STOCK":
//
//                rawData = reportRepository.getLowStockItems();
//
//                break;
//
//            case "GET_TOP_CUSTOMERS":
//
//                rawData = reportRepository.getTopCustomers();
//
//                break;
//
//            default:
//
//                return "I'm sorry, I don't have the tools to check that yet. Try asking about stock levels or customers!";
//
//        }
//
//
//
//// 3. Convert to Human Language (Pass 2)
//
//        return generateFriendlyResponse(message, rawData);
//
//
//
//
//
//    }
//
//
//
//    private String generateFriendlyResponse(String originalQuestion, Object data) {
//
//        String summaryPrompt = String.format(
//
//                "You are the BioGen Inventory Assistant. The manager asked: '%s'. " +
//
//                        "The system found this data: %s. " +
//
//                        "Translate this data into a friendly, professional 2-3 sentence summary. " +
//
//                        "If the data is empty, tell them everything looks good!",
//
//                originalQuestion, data.toString()
//
//        );
//
//
//
//        return geminiService.askGemini(summaryPrompt);
//
//    }
//
//
//
//    private String extractAction(String response) {
//
//        if (response.contains("GET_LOW_STOCK")) return "GET_LOW_STOCK";
//
//        if (response.contains("GET_SALES_REPORT")) return "GET_SALES_REPORT";
//
//        if (response.contains("GET_TOP_CUSTOMERS")) return "GET_TOP_CUSTOMERS";
//
//        return "UNKNOWN";
//
//    }
//
//
//
//}

package com.biogenholdings.InventoryMgtSystem.services.impl;

import com.biogenholdings.InventoryMgtSystem.services.ChatService;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.web.reactive.function.client.WebClient;
import java.util.Map;

@Service
@RequiredArgsConstructor
public class ChatServiceImpl implements ChatService {

    private final WebClient.Builder webClientBuilder;

    @Override
    public Object process(String message) {
        // We no longer need repositories or intent logic here.
        // We just send the question to our Python AI Agent.

        String pythonApiUrl = "http://localhost:8000/ai/chat";

        try {
            Map<String, String> requestBody = Map.of("message", message);

            // Call the Python FastAPI service
            Map<String, Object> pythonResponse = webClientBuilder.build()
                    .post()
                    .uri(pythonApiUrl)
                    .bodyValue(requestBody)
                    .retrieve()
                    .bodyToMono(Map.class)
                    .block();

            // Return the friendly response generated by the Python Agent
            return pythonResponse.get("response");

        } catch (Exception e) {
            System.err.println("Error communicating with AI Agent: " + e.getMessage());
            return "I'm having trouble connecting to my brain right now. Please try again in a moment.";
        }
    }
}