package com.biogenholdings.InventoryMgtSystem.services.impl;

import com.biogenholdings.InventoryMgtSystem.services.ChatService;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.web.reactive.function.client.WebClient;
import java.util.Map;

@Service
@RequiredArgsConstructor
public class ChatServiceImpl implements ChatService {

//    private final WebClient.Builder webClientBuilder;
//
//    @Override
//    public Object process(String message) {
//        // We no longer need repositories or intent logic here.
//        // We just send the question to our Python AI Agent.
//
//        String pythonApiUrl = "http://localhost:8000/ai/chat";
//
//        try {
//            Map<String, String> requestBody = Map.of("message", message);
//
//            // Call the Python FastAPI service
//            Map<String, Object> pythonResponse = webClientBuilder.build()
//                    .post()
//                    .uri(pythonApiUrl)
//                    .bodyValue(requestBody)
//                    .retrieve()
//                    .bodyToMono(Map.class)
//                    .block();
//
//            // Return the friendly response generated by the Python Agent
//            return pythonResponse.get("response");
//
//        } catch (Exception e) {
//            System.err.println("Error communicating with AI Agent: " + e.getMessage());
//            return "I'm having trouble connecting to my brain right now. Please try again in a moment.";
//        }
//    }
}